sudo: false
language: node_js
node_js:
  - stable
cache: npm
before_install:
  - npm install
install:
  - npm install hexo-wordcount --save
  - npm audit fix
  - npm audit fix --force
  - npm audit

  - npm install hexo-generator-json-content --save
  - npm audit fix
  - npm audit fix --force
  - npm audit

  - npm install hexo-generator-feed --save
  - npm audit fix
  - npm audit fix --force
  - npm audit

  - npm install hexo-generator-sitemap --save
  - npm audit fix
  - npm audit fix --force
  - npm audit

  - npm install hexo-generator-baidu-sitemap --save
  - npm audit fix
  - npm audit fix --force
  - npm audit
branches:
  only:
    - main
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on: main
  local-dir: public
