sudo: false
language: node_js
node_js:
  - stable
cache: npm
before_install:
  - npm install
install:
  - npm install hexo-renderer-pug hexo-renderer-stylus --save
  - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-baidu-sitemap --save
  - npm install hexo-neat --save
  - npm install hexo-abbrlink --save
  - npm audit
branches:
  only:
    - main
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on: main
  local-dir: public
