sudo: false
language: node_js
node_js:
  - stable
cache: npm
branches:
  only:
    - sources
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on: main
  local-dir: public
