sudo: false
language: node_js
node_js:
  - stable
cache: npm
install:
  - npm install hexo-wordcount
  - npm install hexo-generator-json-content
  - npm install hexo-generator-feed
  - npm install hexo-generator-sitemap
  - npm install hexo-generator-baidu-sitemap
branches:
  only:
    - main
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on: main
  local-dir: public
